version: '3.7'

services:

  fix-file-permissions:
    image: alpine:${ALPINE_TAG:-latest}
    hostname: fix-file-permissions
    command: >
      sh -c "chown -R 1000 /var/jenkins_home &&
             chgrp -R 1000 /var/jenkins_home &&
             chown 1000 /var/jenkins_home/lost\+found &&
             chgrp 1000 /var/jenkins_home/lost\+found &&
             echo File Permissions changed"
    volumes:
    - jenkins-data:/var/jenkins_home
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none

volumes:
  jenkins-data:
    external: true
    name: ${JENKINS_DATA:-jenkins-data}
