version: '3.7'

services:
  ubuntu:
    image: centos:${CENTOS_TAG:-latest}
    volumes:
    - nexus-data:/nexus-data
    command: chown -R 1000 /nexus-data && chgrp -R 1000 /nexus-data
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
volumes:
  jenkins-data:
    external: true
