version: '3.7'
services:
  httpbin:
    image: citizenstig/httpbin
    ports:
      - 8000:8000
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${JENKINS_SUB_DOMAIN:-httpbin}.${DOMAIN_NAME:-docker.usc.edu}
        - com.df.httpsOnly=true
        - com.df.port=8000
        - com.df.xForwardedProto=true
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
