version: '3.7'

services:

  jenkins-swarm-agent:
    image: vfarcic/jenkins-swarm-agent:${JENKINS_SWARM_AGENT_TAG:-latest}
#    hostname: jenkins-swarm-agent
    environment:
    - COMMAND_OPTIONS=-master http://${JENKINS_IP:-jenkins:8080}${JENKINS_PATH:-/jenkins} -username ${MASTER_USER:-admin} -passwordEnvVariable PASSWORD_ENVVAR -labels 'docker' -executors 5
    - PASSWORD_ENVVAR=${MASTER_PASS:-admin}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - workspace:/workspace
    networks:
    - docker-proxy
    deploy:
      mode: global
volumes:
  workspace:
    external: true
networks:
  docker-proxy:
    external: true
