version: '3.7'
services:
  hello-world:
    image: tutum/hello-world:${HELLO_WORLD_TAG:-latest}
    environment:
      - VIRTUAL_HOST=hello-world.docker.usc.edu
      - VIRTUAL_PORT=80
    networks:
      web-bus:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
networks:
  web-bus:
    external:
      name: web-bus
