FROM tourgeek/ubuntu:latest
ENV JAVA_VERSION=8u232
ENV JDK_VERSION=1.8.0_232
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/

RUN apt update && apt install -y openjdk-8-jdk
# RUN apt install -y icedtea-8-plugin