version: '3.7'

services:
  docker-proxy:
    image: uscdev/docker-proxy
#    command: sleep 36000
    ports:
    - "2376:2376"
    networks:
    - docker-proxy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    secrets:
    - ca.pem
    - server-key.pem
    - server-cert.pem
    environment:
      CA_CRT: /run/secrets/ca.pem
      SERVER_KEY: /run/secrets/server-key.pem
      SERVER_CRT: /run/secrets/server-cert.pem
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  docker-proxy:
    external: true
secrets:
  ca.pem:
    external: true
  server-key.pem:
    external: true
  server-cert.pem:
    external: true
