version: "3.7"

services:

  proxy:
    image: dockerflow/docker-flow-proxy:18.11.07-15
    ports:
    - 80:80
    networks:
    - proxy
    environment:
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
      CONNECTION_MODE: ${CONNECTION_MODE:-http-keep-alive}
    deploy:
      replicas: 1

  swarm-listener:
    image: dockerflow/docker-flow-swarm-listener:18.11.28-19
    networks:
    - proxy
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
    - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
