version: '3.7'

services:
  helloworld1:
    hostname: helloworld1
    image: mendhak/http-https-echo:${HTTP_ECHO_TAG:-latest}
    networks:
    - proxy
    deploy:
      replicas: 2
      labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.httpsOnly.1=true
      - com.df.serviceDomain.1=hello-world.${DOMAIN_NAME:-docker.usc.edu}
      - com.df.port.1=80
      - com.df.httpsOnly.2=true
      - com.df.serviceDomain.2=helloworld.${DOMAIN_NAME:-docker.usc.edu}
      - com.df.port.2=80
  helloworld2:
    hostname: helloworld2
    image: mendhak/http-https-echo:${HTTP_ECHO_TAG:-latest}
    networks:
    - proxy
    deploy:
      replicas: 1
      labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.httpsOnly.1=true
      - com.df.servicePath.1=/hello-world
      - com.df.reqPathSearchReplace.1=/hello-world,/goodbye
      - com.df.port.1=80
      - com.df.httpsOnly.2=true
      - com.df.servicePath.2=/helloworld
      - com.df.port.2=80
  helloworld3:
    hostname: helloworld3
    image: mendhak/http-https-echo:${HTTP_ECHO_TAG:-latest}
    networks:
    - proxy
    deploy:
      replicas: 1
      labels:
      - com.df.notify=true
      - com.df.distribute=true
      - com.df.httpsOnly.1=true
      - com.df.serviceDomain.1=bye.${DOMAIN_NAME:-docker.usc.edu}
      - com.df.servicePath.1=/bye
      - com.df.reqPathSearchReplace=/hello/,/
      - com.df.port.1=80
      - com.df.httpsOnly.2=true
      - com.df.serviceDomain.1=hello.${DOMAIN_NAME:-docker.usc.edu}
      - com.df.servicePath.2=/hello
      - com.df.port.2=80
networks:
  proxy:
    external: true
