version: '3.7'
services:
  iperf:
    image: networkstatic/iperf3:${IPERF_TAG:-latest}
    command: "-s"
    ports:
      - 5201:5201
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==${NODE01}

