version: '3.7'
services:
  db:
    image: mysql:${ANGUALR_MYSQL_TAG:-latest}
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/tt_secrets.txt
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - wd-db-data6:/var/lib/mysql
    secrets:
      - tt_secrets.txt
secrets:
  tt_secrets.txt:
    external: true
volumes:
  wd-db-data6:
    external:
      name: wd-db-data6