version: '3.7'

services:
  modsecurity:
    image: fareoffice/modsecurity
    environment:
      - PROXY_UPSTREAM_HOST=hello-world:80
      - PARANOIA=3
      - SEC_RULE_AFTER_FOO=SecRuleRemoveById 920420
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - log.security=true   # Note - This logs security data
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=hello-proxy.${DOMAIN_NAME:-docker.usc.edu}
        - com.df.port.1=80
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
  hello-world:
    image: tutum/hello-world:${HELLO_WORLD_TAG:-latest}
    networks:
      - proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true
