version: '3.7'

services:

  main:
    image: vfarcic/jenkins-swarm-agent:${JENKINS_SWARM_AGENT_TAG:-latest}
    environment:
      - COMMAND_OPTIONS=-master http://ec2-54-213-228-175.us-west-2.compute.amazonaws.com:50000 -username admin -passwordEnvVariable PASSWORD_ENVVAR -labels 'docker' -executors 5
      - PASSWORD_ENVVAR=admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - workspace:/workspace
    deploy:
      mode: global
    networks:
      - proxy
volumes:
  workspace:
    external: true
networks:
  proxy:
    external:
      name: proxy

