FROM tourgeek/ubuntu:latest
ENV JAVA_VERSION=11
ENV JDK_VERSION=11.0.13
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/

RUN apt update && apt install -y openjdk-11-jdk
# RUN apt install -y icedtea-8-plugin