static_resources:
  listeners:
    - name: nexus-demo
      address:
        socket_address: { address: 0.0.0.0, port_value: 80 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route:
                            auto_host_rewrite: true
                            cluster: nexus_service
                http_filters:
                  - name: envoy.lua
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.filter.http.lua.v2.Lua
                      inline_code: |
                        local mylibrary = require("lib.mylibrary")

                        function envoy_on_request(request_handle)
                          mylibrary.handleRequest(request_handle)
                        end

                        function envoy_on_response(response_handle)
                          mylibrary.handleResponse(response_handle)
                        end
                  - name: envoy.router
                    typed_config: {}
  clusters:
  - name: nexus_service
    connect_timeout: 5s
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
#    http2_protocol_options: {}  # Fails with this enabled
    upstream_connection_options:
      # configure a TCP keep-alive to detect and reconnect to the admin
      # server in the event of a TCP socket half open connection
      tcp_keepalive: {}
    load_assignment:
      cluster_name: nexus_service
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: nexus
                port_value: 80

admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 127.0.0.1, port_value: 15000 }
