version: '3.7'

services:
  hello-world:
    image: tutum/hello-world
    networks:
      - proxy
    ports:
      - 8080:80
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=hello-world.swarm.jbundle.org
        - com.df.port=80
networks:
  proxy:
    external: true
