version: '3.7'
services:
  mysql:
    image: mysql:${MYSQL_TAG:-latest}
    ports:
      - 3306:3306
    volumes:
      - ${USC_BLOCK_DIR:-/docker-nfs}/mysql:/var/lib/mysql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname==${NODE02}
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
